cat > k8s/deployment.yaml <<'YAML'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hola-api
  template:
    metadata:
      labels:
        app: hola-api
    spec:
      containers:
        - name: hola-api
          image: us-central1-docker.pkg.dev/project-95fcfc61-ea90-4e73-8c4/demo-repo/hola-api:e25eb2c
          ports:
            - containerPort: 8080
YAML
